name: PS4 HEN Payload

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      zip: ps4-hen-vtx
      zip_glob: ps4-hen-*.bin
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          submodules: recursive # Ensure submodules are checked out

      - name: Set execute permissions for scripts
        run: chmod +x build.sh download_prx.sh

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc zip

      - name: Build PS4SDK
        run: |
          cd ps4-payload-sdk/libPS4
          make clean && make
         
      - name: Build and package binaries
        run: |
          ./download_prx.sh
          VERSIONS="505 672 700 701 702 750 751 755 800 801 803 850 852 900 903 904 950 951 960 1000 1001 1050 1070 1071 1100 1102 1150 1152 1200 1202"
          for VERSION in $VERSIONS; do
            ./build.sh $VERSION
          done
          zip ${{ env.zip }}.zip ${{ env.zip_glob }}

      - name: Upload payload
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: ps4-hen-vtx
          path: ${{ env.zip_glob }}

      - name: Release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PRERELEASE_FLAG=""
          if [ "${GITHUB_REF}" != "refs/heads/Multi-HEN" ]; then
            PRERELEASE_FLAG="-p"
          fi

          gh release create $PRERELEASE_FLAG HEN-1.0${{ github.run_number }} ps4-hen-vtx.zip \
            --target ${{ github.sha }} \
            -t HEN-1.0${{ github.run_number }}
